# Generated by Django 5.0.7 on 2024-07-16 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Todos",
            new_name="Todo",
        ),
    ]
